param(
    [string]$TaskName = 'LongtermMonthlySpotifyProfile',
    [string]$At = '10:30',
    [ValidateRange(1, 28)]
    [int]$DayOfMonth = 1,
    [switch]$Uninstall,
    [switch]$WhatIf
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Monthly Spotify taste pull + deep profile rebuild (1st of month by default).
# Uses a daily trigger that no-ops unless today's day-of-month matches, because
# Windows Scheduled Task "monthly" day triggers are awkward across months.

function Quote-TaskArg {
    param([string]$Value)
    return ('"{0}"' -f ($Value -replace '"', '""'))
}

if ($Uninstall) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "Removed scheduled task '$TaskName' (if it existed)."
    exit 0
}

if ($At -notmatch '^\d{2}:\d{2}$') {
    throw 'At must use HH:mm 24-hour format, for example 10:30.'
}

$runnerPath = Join-Path $PSScriptRoot 'run-monthly-spotify-profile.ps1'
$wrapperPath = Join-Path $PSScriptRoot 'run-monthly-spotify-profile-if-due.ps1'
if (-not (Test-Path -LiteralPath $runnerPath)) {
    throw "Missing script at $runnerPath"
}
if (-not (Test-Path -LiteralPath $wrapperPath)) {
    throw "Missing script at $wrapperPath"
}

# Keep the if-due wrapper's day-of-month in sync with -DayOfMonth.
$wrapper = @"
param()
Set-StrictMode -Version Latest
`$ErrorActionPreference = 'Stop'

# Called daily by LongtermMonthlySpotifyProfile; only runs the real job on the
# configured day-of-month. Regenerated by install-monthly-spotify-profile-scheduled-task.ps1.

`$dueDay = $DayOfMonth
if ((Get-Date).Day -ne `$dueDay) { exit 0 }
& (Join-Path `$PSScriptRoot 'run-monthly-spotify-profile.ps1') -AllOwners
"@
Set-Content -LiteralPath $wrapperPath -Value $wrapper -Encoding UTF8

$powershell = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$taskArgs = ('-NoProfile -ExecutionPolicy Bypass -File {0}' -f (Quote-TaskArg $wrapperPath))
$parts = $At.Split(':')
$atDate = Get-Date -Hour ([int]$parts[0]) -Minute ([int]$parts[1]) -Second 0

if ($WhatIf) {
    Write-Host ('Would create monthly scheduled task "{0}" on day {1} at {2}' -f $TaskName, $DayOfMonth, $At)
    Write-Host ('Task command: {0} {1}' -f $powershell, $taskArgs)
    exit 0
}

$trigger = New-ScheduledTaskTrigger -Daily -At $atDate
$action = New-ScheduledTaskAction -Execute $powershell -Argument $taskArgs -WorkingDirectory $PSScriptRoot
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -WakeToRun `
    -MultipleInstances IgnoreNew `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -RunOnlyIfNetworkAvailable

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings `
    -Description ("Monthly Longterm Spotify pull + taste profile (day {0} at {1}). Log: %USERPROFILE%\.longterm\logs\monthly-spotify-profile.log" -f $DayOfMonth, $At) `
    -Force | Out-Host

Write-Host ("Registered scheduled task '{0}' (day {1} of each month at {2})." -f $TaskName, $DayOfMonth, $At)
Write-Host 'Log: %USERPROFILE%\.longterm\logs\monthly-spotify-profile.log'
Write-Host 'Wrapper: scripts/run-monthly-spotify-profile-if-due.ps1'
