param()
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Called daily by LongtermMonthlySpotifyProfile; only runs the real job on the
# configured day-of-month. Regenerated by install-monthly-spotify-profile-scheduled-task.ps1.

$dueDay = 1
if ((Get-Date).Day -ne $dueDay) { exit 0 }
& (Join-Path $PSScriptRoot 'run-monthly-spotify-profile.ps1') -AllOwners
